# Base Services
version: "3.3"
services:

  # Base Services
version: "3.3"
services:

  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    command: -H unix:///var/run/docker.sock
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/binkocd/docker/portainer/data:/data
      - /home/binkocd/docker/shared:/shared
    environment:
      - TZ=America/Los_Angeles


  watchtower:
    container_name: watchtower
    restart: always
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30