# Media Services
version: '3'
services:

  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=100
      - VERSION=docker
    volumes:
      - /share/homes/binkocd/docker/plexms:/config
      - /share/CACHEDEV1_DATA:/tv
      - /share/CACHEDEV1_DATA:/movies
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    restart: unless-stopped

  tautulli:
    container_name: tautulli
    restart: always
    image: linuxserver/tautulli
    volumes:
      - /share/homes/binkocd/docker/tautulli/config:/config
      - /share/homes/binkocd/docker/tautulli/logs:/logs:ro
      - /share/homes/binkocd/docker/shared:/shared
    ports:
      - "8181:8181"
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Los_Angeles
