# This Docker Compose file contains the following services:
# - wireguard: A self-hosted VPN server based on wg-easy.
#
# This file uses the following environment variables, which should be defined in a .env file:
# - PUID: The user ID to run the container as.
# - PGID: The group ID to run the container as.
# - TZ: The timezone for the containers.
# - CONFIG_DIR: The path for Wireguard's configuration files.
#
# This file also uses a Docker secret for the admin password.
# To create the secret, run the following command on your Docker host:
# echo "your_strong_password" | docker secret create wg_admin_password -
#

# Define common environment variables using an extension field.
x-common-env: &common-env
  PUID: ${PUID}
  PGID: ${PGID}
  TZ: ${TZ}

services:
  wireguard:
    image: ghcr.io/wg-easy/wg-easy:latest
    container_name: wg-easy
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      <<: *common-env
      # Reference the secret to set the admin password
      WG_ADMIN_PASSWORD_FILE: /run/secrets/wg_admin_password
    volumes:
      - ${CONFIG_DIR}/.wg-easy:/etc/wireguard
    ports:
      - 51820:51820/udp
      - 51821:51821/tcp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:51821/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    secrets:
      - wg_admin_password

# Define the secrets at the top level
secrets:
  wg_admin_password:
    external: true